### ISSUE TITLE
Getting a 422 error when requesting assignments

### ISSUE THREAD

**Issue by tmharryfrancis** [dan1elhughes/forecast-promise#16]
Hey!

Been playing with the API and everything was working as expected. I noticed on Friday that the API started returning a 422 when requesting assignments. The other methods work as I'd expect (Clients and Projects for example).

`Failed to load resource: the server responded with a status of 422 () - https://api.forecastapp.com/assignments?start_date=2021-03-22&end_date=2050-03-02`

I've changed nothing since it was working, so assume something on the API end has changed?

Would be great if someone could give me some pointers on this, or work out if the API has just broken backwards compatibility.

Thanks, Harry.

**Comment by xmnlab** [comment]
same problem in other lib related as well https://github.com/singer-io/tap-harvest-forecast/issues/13

**Comment by tmharryfrancis** [comment]
Thanks for that @xmnlab.

**Solution**: Their is now a date range limit of 6 months on assignment calls.
