### ISSUE TITLE
Assignments start_date and end_date return absolutely the wrong range

### ISSUE THREAD

**Issue by 19007361** [dan1elhughes/forecast-promise#8]
/assignments?start_date=2019-08-18&end_date=2019-09-14

Returns me JSON with the following:

```
{
  "assignments": [{
    ...
    "start_date": "2019-02-01",
    "end_date": "2019-12-31",
    ...
    "start_date": "2019-05-02",
    "end_date": "2019-12-31",
    ...
    "start_date": "2019-06-29",
    "end_date": "2019-12-31",
    ...
    "start_date": "2019-09-02",
    "end_date": "2019-09-06",
    ...
    "start_date": "2019-04-23",
    "end_date": "2019-12-31",
    ...
    "start_date": "2019-05-27",
    "end_date": "2019-12-31",
    ...
    "start_date": "2019-06-18",
    "end_date": "2020-01-31",
    ...
    "start_date": "2019-06-18",
    "end_date": "2019-09-15",
    ...
    }]
}
```

**Comment by dan1elhughes** [comment]
It looks like all those assignments include periods of time in which your query applies. For example, if you have an assignment from 1pm to 6pm, and you query "get me assignments between 4pm and 5pm", it makes sense for that assignment to be returned as it is included in the time window.

This is part of the Forecast API, and not something I'm adding explicitly. If you'd like to PR an option to filter out this sort of thing I'd be happy to review it 👍

**Comment by 19007361** [comment]
First off thank you very much for responding so quickly to this issue.

I see now what you mean, I assumed the range would be whatever falls inside that range and not that the range is a smaller part of the whole.
